### ISSUE TITLE
댓글 새로고침 버튼 만들기

### ISSUE THREAD

**Issue by Poxios** [Convergence-Specialization/CS-Front#105]
적절한 기획이 필요합니다 🥇

**Comment by ywoo121** [comment]
이거 댓글 작성하기 누르면 새로고침 자동으로 되는 거는 없고 무조건 수동으로 버튼 눌러서 새로고침해야 되나여

**Comment by Poxios** [comment]
네 일부러 그렇게 했습니다 돈나갈까봐ㅠ

**Comment by eunsoA** [comment]
엥 댓글 작성하면 자동으로 새로고침 되던데여

**Comment by Poxios** [comment]
그거 그런 척 한겁니다ㅠ
