### ISSUE TITLE
공지사항 글쓰기 페이지

### ISSUE THREAD

**Issue by eunsoA** [Convergence-Specialization/CS-Front#132]
학생회가 : 공지사항에서 -> 글작성 시
위에 있는건 사진 첨부 안했을 시
아래있는건 사진 첨부 시 (5장 이상은 nowrap으로 넘어감)

![image](https://user-images.githubusercontent.com/74090200/107614763-485ad400-6c8e-11eb-8c94-7ef217c63522.png)
![image](https://user-images.githubusercontent.com/74090200/107614776-501a7880-6c8e-11eb-954d-a4926995042b.png)

**Comment by kimjunha1231** [comment]
src\Component\Board\Announcement\Normal\Create.js
