### ISSUE TITLE
융합전공 소개 기획

### ISSUE THREAD

**Issue by eunsoA** [Convergence-Specialization/CS-Front#133]
융합 전공 소개부분에 들어갈 내용 기획 덜함..
이거 뭐넣을지 좋은 거있으면 보내주세요,,,,,

**Comment by ywoo121** [comment]
진짜 살짝 노답임,,..

**Comment by Poxios** [comment]
학생회 찬스 한번 더..??

**Comment by eunsoA** [comment]
근데 학생회분들 공지사항 빼고 학과소개쪽은 별로 관심없어 보이지 않았어,..,?

**Comment by Poxios** [comment]
학생회에게 자료 받으면 넣자!
