### ISSUE TITLE
아이폰 사파리로 구글 로그인

### ISSUE THREAD

**Issue by ywoo121** [Convergence-Specialization/CS-Front#137]
아이폰 사파리로 구글 로그인하면 로딩하다가 중간에 기본 로그인 페이지로 돌아갔다가 그 다음에 메인페이지로 감
이러면 걍 로딩중으로 해야하는 거 아닌가

--------------------------
갤럭시로도 이런지 확인해주세여

**Comment by eunsoA** [comment]
헹

**Comment by ywoo121** [comment]
사실 이건 은소의 의견이었음. 뭔 소린지 이해불가면 은소한테 확인 바람요

**Comment by Poxios** [comment]
이해가안됨니다
