### ISSUE TITLE
마이페이지 CSS 부분 해결점요ㅠ

### ISSUE THREAD

**Issue by Poxios** [Convergence-Specialization/CS-Front#146]
![image](https://user-images.githubusercontent.com/62606632/107734015-c4f9bb00-6d3f-11eb-8ccf-5d0ae48f626c.png)
여기 간격이나 그런것들이 조금 어색한듯해요..!

**Comment by Poxios** [comment]
해결해주실분 assign 본인 제외하고 빼주시면 됩니다..!

**Comment by eunsoA** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ맞아 이거 간격이랑 글씨 이상해,.,

**Comment by eunsoA** [comment]
요느낌으로 수정하면될것같아여

![image](https://user-images.githubusercontent.com/74090200/107750380-4b71c500-6d5f-11eb-9563-738b28ac02e3.png)

**Comment by eunsoA** [comment]
+ 마이페이지에서 본인 학번이 나오도록 수정필요

**Comment by kimjunha1231** [comment]
저는 흠 일단 내일 시간 되면 어사인하고 할게요..
