### ISSUE TITLE
가입할 때 정보 넣는 곳에 실제 정보와 다르게 입력할 시 불이익 준다

### ISSUE THREAD

**Issue by Poxios** [Convergence-Specialization/CS-Front#164]
기재하는게 어때?

**Comment by eunsoA** [comment]
학번 1234 같은거 막기

**Comment by eunsoA** [comment]
신고 몇번이상먹은 사람은 댓글 작성 글작성에 기한 제한두기?

**Comment by eunsoA** [comment]
+ 이건 다른건데 도배 방지를 위해 댓글 작성시 일정시간 간격 두도록 제한 두기

**Comment by ywoo121** [comment]
- 일단 학번 제대로 기재하도록 하는 게 제일 중요할 거 같구
 - 근데 일정시간 간격을 둔다고 하면 댓글 작성보다는 게시글 작성할 때 주는 게 더 낫지 않을까여

**Comment by Poxios** [comment]
시간 간격으로 동작하는건 나아중에 넣는게 좋을듯합니다!

**Comment by Poxios** [comment]
학번 8자리만 일단 받자.

**Comment by eunsoA** [comment]
- 학번 8자리 받는지 확인
- 시간 간격으로 동작 할건지 안할건지 확인
- 이후 이슈 닫기
