### ISSUE TITLE
제목 최대 길이 수정

### ISSUE THREAD

**Issue by Poxios** [Convergence-Specialization/CS-Front#168]
![image](https://user-images.githubusercontent.com/62606632/107864690-191cb080-6ea2-11eb-8cb7-909514546659.png)
오른쪽 위!

**Comment by eunsoA** [comment]
완료!

**Comment by eunsoA** [comment]
이거 github.io에서는 최대길이 수정되어보이는데 앱에서는 안보여요!

**Comment by eunsoA** [comment]
이거 github.io에서는 최대길이 수정되어보이는데 앱에서는 수정된 최대길이로 안보임
