### ISSUE TITLE
내가작성한 글 -> 더보기 -> 삭제/ 신고/ 취소박스

### ISSUE THREAD

**Issue by eunsoA** [Convergence-Specialization/CS-Front#206]
좀 작은거 같기도..?
이거 연우가 좀 수정하고있었나?
![image](https://user-images.githubusercontent.com/74090200/108217118-96804380-7176-11eb-8162-ab693d070ab4.png)

**Comment by ywoo121** [comment]
아 저거 수정해봤는데도 구려서 그냥 원래대로 놔두고 있었어여
