### ISSUE TITLE
전과게시판 상단에 픽스된건 어떤가여?

### ISSUE THREAD

**Issue by eunsoA** [Convergence-Specialization/CS-Front#209]
![image](https://user-images.githubusercontent.com/74090200/108217838-66857000-7177-11eb-82ec-5e03734b850d.png)

**Comment by kimjunha1231** [comment]
![image](https://user-images.githubusercontent.com/74090222/108219959-946bb400-7179-11eb-8415-2cd702e577ff.png)

**Comment by kimjunha1231** [comment]
원래 상단에 있는거 아닌가요?

**Comment by Poxios** [comment]
네비바처럼 완전 픽스 말하는거 아닌가?

**Comment by kimjunha1231** [comment]
아 그런가?

**Comment by eunsoA** [comment]
ㅇㅇ완전픽스 말하는거 마즘

**Comment by ywoo121** [comment]
좋아영
