### ISSUE TITLE
의논하고 수정해야할 사안들

### ISSUE THREAD

**Issue by eunsoA** [Convergence-Specialization/CS-Front#211]
- [x] 1. 전과게시판 제목에서 줄간격 수정해야함.

- [x] 2. 이미 공감한글/댓글입니다 박스 왜 파란선이 박스선에 보이는건지 확인 필요(박스 구린데 왜 구린지..?)

+박스 가로길이 수정필요

- [x] 더보기 삭제/신고/취소

4.팀소개 사진어케할지

5.이제 아이콘도 다시한번 물어봐야한다.

6.학생회에게 공지사항관련해서 물어볼거면

(1) 학생회랑 더 말해보기 -> 금요일 오티 이후 회의 필요

7. 전게 정리 마무리되면 -> 융게 다시 정리필요.

**Comment by ywoo121** [comment]
1. 줄간격 수정 완료했숨

**Comment by Poxios** [comment]
- [ ] 이 문법으로 사용하면
- [ ] 편합니다

**Comment by ywoo121** [comment]
우왕

**Comment by eunsoA** [comment]
오왕

**Comment by kimjunha1231** [comment]
우오아앙
