### ISSUE TITLE
로그인 화면에 쓰는 동그란 말이 필요합니다.

### ISSUE THREAD

**Issue by kimjunha1231** [Convergence-Specialization/CS-Front#212]
![image](https://user-images.githubusercontent.com/74090222/108221218-e2cd8280-717a-11eb-82ba-889d47af1ffe.png)

**Comment by ywoo121** [comment]
![image](https://user-images.githubusercontent.com/71367047/108315399-b65b4a00-71fe-11eb-944e-0cf2ed252d00.png)

이거 말씀하시는 건가여

**Comment by eunsoA** [comment]
사진 newHorese로 이름도있어여 융게 리스트뷰 확인해 보세여

**Comment by eunsoA** [comment]
이건 radius를 쓸지 아예 잘라서 들어갈 지 생각좀 해봐야할듯

**Comment by kimjunha1231** [comment]
넵 radius는 동그랗게 하기 힘들어서

**Comment by kimjunha1231** [comment]
Xd에서 해야할듯 합니다

**Comment by eunsoA** [comment]
이거 수정한사진이ㅆ었던것같은데 연우님께 여쭤볼게여
