### ISSUE TITLE
로그인 안해서 접근 불가한 페이지에서

### ISSUE THREAD

**Issue by Poxios** [Convergence-Specialization/CS-Front#214]
![image](https://user-images.githubusercontent.com/62606632/108306233-134f0400-71ef-11eb-9415-e6740fad0f39.png)
* 이 사이트를 이용하는 보통의 사람들이라면 여기서 회원가입을 누를 것임.
* 그러나 회원가입 창은 이메일 밖에 없음. 상당히 귀찮기 때문에 이용하지 않을 가능성.
* 따라서 회원가입에도 구글 로그인을 넣거나, 아예 이 페이지에서 회원가입 버튼을 빼서 로그인 페이지로 이동 후 구글 로그인이 가능하도록 제안하는 바.

**Comment by kimjunha1231** [comment]
회원가입 버튼 빼는거 괜찮네여

**Comment by eunsoA** [comment]
나도 회원가입버튼뺴버리는거 한표

**Comment by ywoo121** [comment]
동의

**Comment by Poxios** [comment]
하실분~~ Assign좀
