### ISSUE TITLE
댓글

### ISSUE THREAD

**Issue by eunsoA** [Convergence-Specialization/CS-Front#247]
오른쪽에 마진들어가있어서 글이 너비의 60%밖에 안보임 이건 지금 준하가 실시간으로 수정중

**Comment by kimjunha1231** [comment]
이거 머지 끝나면 댓글 길이 어떤지 확인해주십쇼 다 괜찮으면 클로즈합시다

**Comment by eunsoA** [comment]
요건 주말에 같이 확인하고 클로즈!
