### ISSUE TITLE
마이페이지 -> 내가 쓴 글로 들어가서 더보기 버튼 눌렀을 때

### ISSUE THREAD

**Issue by ywoo121** [Convergence-Specialization/CS-Front#259]
- 게시판에서 내가 쓴 글 찾아서 들어갈 때 (정상적으로 삭제가 뜸)
![image](https://user-images.githubusercontent.com/71367047/109271306-ae308980-7852-11eb-9008-f9712fe0359a.png)

- 마이페이지 -> 내가 쓴 글 으로 들어갈 때 (신고가 뜬다 띠용)
![image](https://user-images.githubusercontent.com/71367047/109271372-c6080d80-7852-11eb-9df2-dd91fc5af500.png)

**Comment by kimjunha1231** [comment]
이거 작성자가 익명으로 뜨는거랑 똑같은 원리 아닐까 작성자 본인취급이 아닌 익명 처리가 되어서ㅠ

**Comment by ywoo121** [comment]
헐 그러네
이 이슈 삭제해야징
