### ISSUE TITLE
내일 일요일(28) 말할내용

### ISSUE THREAD

**Issue by eunsoA** [Convergence-Specialization/CS-Front#283]
- [x] 연우가만든 카드뉴스 멘트 확인 + 우리이름넣기
- [x] 융특 슝 소개페이지
- [x] 홈화면추가+ 앱설치 설명  카드뉴스형식? -> 이건 공지사항에 들어갈거니까 카드뉴스가 나을수도?
- [x] 회원가입시 융특인가에 대한 조건을걸으냐? 융특조건보다는 숭실대학교 학생조건이 더 나을것 같은데 숭실대학교학생이라는 인증수단을 무엇으로 할 것 인가?  -> 졸라중요별표세개임 내일필수로 가장많이 논의가 필요한 부분
- [x] 회원탈퇴 
- [x] 핫게시판
- [x] 인스타로 진행하지 않는 이벤트, 행사들에 대한 보안문제
- [x] 약관정리 -> 졸라중요 꼭내일필수로해야함

**Comment by Poxios** [comment]
여기 졸라중요하다고써있는부분들 얘기가 안됐군..
