### ISSUE TITLE
전과게시판

### ISSUE THREAD

**Issue by eunsoA** [Convergence-Specialization/CS-Front#284]
이거 없으면 로딩 아이콘 말고 없다고 띄우기(like 알림페이지 알림 모두 확인했을 때 처럼)
![image](https://user-images.githubusercontent.com/74090200/109395056-b29d9500-796d-11eb-9cf3-dccb085cafbd.png)

**Comment by Poxios** [comment]
이거는 일부러 이렇게 안한게 우리가 글 하나씩만 써도 그런 상황이 없어서!

**Comment by eunsoA** [comment]
ㅇㅋ
